[project]
name = "internetwebsearchermcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "crawl4ai>=0.7.4",
    "fastmcp>=2.11.3",
    "pre-commit>=4.3.0",
    "requests>=2.32.5",
    "wikipedia>=1.4.0",
]
